install.packages("sp")
install.packages("rgdal")
install.packages("spdep")
install.packages("tmap")
install.packages("ggplot2")
install.packages("ggrepel")
install.packages("starma")
install.packages("gstat")
install.packages('spDataLarge', repos='https://nowosad.github.io/drat/', type='source')
